version: '3.8'

# Services
services:

  # PHP Service
  php:
    build:
      dockerfile: php-dockerfile
    volumes:
      - '.:/var/www/html'

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 8910:80
    links:
      - 'php'
    volumes:
      - '.:/var/www/html'
      - './nginx-conf:/etc/nginx/conf.d'
    depends_on:
      - php