controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
index:
    path: /hello
    controller: App\Controller\CryptoController::index
